### ISSUE TITLE
Snyk XSS vulnerability

### ISSUE THREAD

**Issue by me-matt** [tabatkins/railroad-diagrams#113]
Snyk is reporting a XSS vulnerability in generator.html. Though this isn't used, html encoding angle brackets in the input is a trivial change.

https://security.snyk.io/vuln/SNYK-JS-RAILROADDIAGRAMS-6282875

**Comment by ashenmagic** [comment]
I believe I've resolved #113. Please take a look at #115 whenever you've got a moment, as it should resolve the XSS vulnerability that Snyk reports in packages that depend on `railroad-diagrams`.

**Comment by tabatkins** [comment]
This is a false positive. All input arguments end up having vulnerable characters escaped in the output; try putting `<script>alert(1)</script>` anywhere in the dingus to see that in action.

The *entire page* is an XSS vulnerability, of a sort - whatever you put into the URL gets dropped directly into the input, which is then `exec()`'d in JS. So you can definitely write a URL like `https://tabatkins.github.io/railroad-diagrams/generator.html#alert(1)` and get an alert popup. That's kinda intentional to the operation of the tool.
