### ISSUE TITLE
Allow to select single/double lines at start and end

### ISSUE THREAD

**Issue by dswd** [tabatkins/railroad-diagrams#18]
It would be great if you could select whether to have single or doulbe lines as the begin and end indicators.
I am not completely sure but I think that the authors of json.org used this to highlight which of the non-terminals can have whitespace between the components.

**Comment by jonathanKingston** [comment]
I had always assumed the distinction was if the diagram didn't contain subtypes. So number and string don't contain anything but low level characters where as objects, arrays and values I would consider "composite types" where they are comprised of multiple other diagrams.

I would like this for the diagrams I have been building at: http://jetson.io

**Comment by tabatkins** [comment]
Hm, all right, that seems consistent.  Yeah, I'm okay with this.  I'll accept a PR if I don't get to it soon.

**Comment by jonathanKingston** [comment]
I wrote the code for the single lines the other day, just trying to think of the best way to hook that up to the diagram function, my two ideas were:

- Add a boolean flag to the last argument to `Diagram`
  - This would have been my preferred route however because of the code looking for just an array of inputs it was a little problematic
- Subclass `Diagram` as `ComplexDiagram`
  - This was going to be my secondary choice as it requires a bit of code duplication in the constructor which is annoying (Will debug further soon).

Just thought it was worth updating you, hopefully to save your time.

**Comment by jonathanKingston** [comment]
@tabatkins let me know what you think.
